name: Deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Chromium for Flutter Web
        run: sudo apt-get update && sudo apt-get install -y chromium-browser

      - name: Build Flutter Web
        run: flutter build web --release

      # docsディレクトリ作成しFlutter Webの成果物をコピー
      - name: Prepare docs directory
        run: |
          rm -rf docs
          mkdir docs
          cp -r build/web/* docs/
          touch docs/.nojekyll

      # 不要なSCSSファイルを削除（Jekyllが処理しようとするのを防ぐ）
      - name: Remove SCSS if present
        run: rm -f docs/assets/css/style.scss

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          jekyll: false
