name: Flutter Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build web
      - run: mkdir -p docs && cp -r build/web/* docs/
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v1
